---
output:
  github_document:
    toc: true  
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  cache = TRUE,
  message = FALSE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "40%"
)

```

# Introduction

Welcome to `relper`, a R package designed to make data preparation, cleaning, and visualization a breeze. 

Created by a senior [statistician](https://vbfelix.github.io/header-about.html), `relper` is a collection of functions that have been refined over the years to provide a comprehensive set of tools for data cleaning and visualization.

With `relper`, you can easily transform and format your data, compute important metrics, check conditions, and even use lovely and varied color palettes. Some of the key features of relper include:

 - **Data transformation and formatting**: offers a variety of functions to help you format your data.

 - **Metrics**: provides functions to compute important metrics, such as the coefficient of variation.

 - **Condition checking**: allows you to check conditions, such as determining if a number is even or odd.

 - **Color palettes**: includes beautiful and varied color palettes, inspired by popular TV series and movies.

 - **ggplot2 integration**: complements ggplot2, e.g., by allowing you to add an identity line to a scatter plot  with single command.

 - **String manipulation**: offers functions to manipulate strings, such as keeping only a specific type of character.

The ultimate goal of `relper` is to simplify data analysis by providing a variety of useful functions that will shorten your steps and make data analysis more efficient. Try `relper`and discover how it can streamline your data analysis workflow.

# Installation

You can install the developer version of `relper` with:

``` r
remotes::install_github("vbfelix/relper")
```
<!-- # Citation -->

<!-- To generate a citation for the package version you are using, you can run -->

<!-- ``` r -->
<!-- citation(package = "galah") -->
<!-- ``` -->









